from django.db import models

class Bilateral(models.Model):
    region_orig = models.CharField(max_length=200)
    region_orig_id = models.IntegerField(default=0)
    region_dest = models.CharField(max_length=200)
    region_dest_id = models.IntegerField(default=0)
    country_orig = models.CharField(max_length=200)
    country_orig_id = models.CharField(max_length=200)
    country_dest = models.CharField(max_length=200)
    country_dest_id = models.CharField(max_length=200)
    regionflow_1990 = models.IntegerField(default=0)
    regionflow_1995 = models.IntegerField(default=0)
    regionflow_2000 = models.IntegerField(default=0)
    regionflow_2005 = models.IntegerField(default=0)
    countryflow_1990 = models.IntegerField(default=0)
    countryflow_1995 = models.IntegerField(default=0)
    countryflow_2000 = models.IntegerField(default=0)
    countryflow_2005 = models.IntegerField(default=0)
    metadata = models.CharField(max_length=200)

class FertilityRates(models.Model):
    countryname = models.CharField(max_length=200)
    countrycode = models.CharField(max_length=200)
    year_1990 = models.FloatField(default=0, null=True)
    year_1991 = models.FloatField(default=0, null=True)
    year_1992 = models.FloatField(default=0, null=True)
    year_1993 = models.FloatField(default=0, null=True)
    year_1994 = models.FloatField(default=0, null=True)
    year_1995 = models.FloatField(default=0, null=True)
    year_1996 = models.FloatField(default=0, null=True)
    year_1997 = models.FloatField(default=0, null=True)
    year_1998 = models.FloatField(default=0, null=True)
    year_1999 = models.FloatField(default=0, null=True)
    year_2000 = models.FloatField(default=0, null=True)
    year_2001 = models.FloatField(default=0, null=True)
    year_2002 = models.FloatField(default=0, null=True)
    year_2003 = models.FloatField(default=0, null=True)
    year_2004 = models.FloatField(default=0, null=True)
    year_2005 = models.FloatField(default=0, null=True)
    year_2006 = models.FloatField(default=0, null=True)
    year_2007 = models.FloatField(default=0, null=True)
    year_2008 = models.FloatField(default=0, null=True)
    year_2009 = models.FloatField(default=0, null=True)
    year_2010 = models.FloatField(default=0, null=True)

class PerWorkerGDP(models.Model):
    countryname = models.CharField(max_length=200)
    countrycode = models.CharField(max_length=200)
    year_1990 = models.FloatField(default=0, null=True)
    year_1991 = models.FloatField(default=0, null=True)
    year_1992 = models.FloatField(default=0, null=True)
    year_1993 = models.FloatField(default=0, null=True)
    year_1994 = models.FloatField(default=0, null=True)
    year_1995 = models.FloatField(default=0, null=True)
    year_1996 = models.FloatField(default=0, null=True)
    year_1997 = models.FloatField(default=0, null=True)
    year_1998 = models.FloatField(default=0, null=True)
    year_1999 = models.FloatField(default=0, null=True)
    year_2000 = models.FloatField(default=0, null=True)
    year_2001 = models.FloatField(default=0, null=True)
    year_2002 = models.FloatField(default=0, null=True)
    year_2003 = models.FloatField(default=0, null=True)
    year_2004 = models.FloatField(default=0, null=True)
    year_2005 = models.FloatField(default=0, null=True)
    year_2006 = models.FloatField(default=0, null=True)
    year_2007 = models.FloatField(default=0, null=True)
    year_2008 = models.FloatField(default=0, null=True)
    year_2009 = models.FloatField(default=0, null=True)
    year_2010 = models.FloatField(default=0, null=True)

class PrimaryEnrollmentRate(models.Model):
    countryname = models.CharField(max_length=200)
    countrycode = models.CharField(max_length=200)
    year_1990 = models.FloatField(default=0, null=True)
    year_1991 = models.FloatField(default=0, null=True)
    year_1992 = models.FloatField(default=0, null=True)
    year_1993 = models.FloatField(default=0, null=True)
    year_1994 = models.FloatField(default=0, null=True)
    year_1995 = models.FloatField(default=0, null=True)
    year_1996 = models.FloatField(default=0, null=True)
    year_1997 = models.FloatField(default=0, null=True)
    year_1998 = models.FloatField(default=0, null=True)
    year_1999 = models.FloatField(default=0, null=True)
    year_2000 = models.FloatField(default=0, null=True)
    year_2001 = models.FloatField(default=0, null=True)
    year_2002 = models.FloatField(default=0, null=True)
    year_2003 = models.FloatField(default=0, null=True)
    year_2004 = models.FloatField(default=0, null=True)
    year_2005 = models.FloatField(default=0, null=True)
    year_2006 = models.FloatField(default=0, null=True)
    year_2007 = models.FloatField(default=0, null=True)
    year_2008 = models.FloatField(default=0, null=True)
    year_2009 = models.FloatField(default=0, null=True)
    year_2010 = models.FloatField(default=0, null=True)

class LaborParticipationRate(models.Model):
    countryname = models.CharField(max_length=200)
    countrycode = models.CharField(max_length=200)
    year_1990 = models.FloatField(default=0, null=True)
    year_1991 = models.FloatField(default=0, null=True)
    year_1992 = models.FloatField(default=0, null=True)
    year_1993 = models.FloatField(default=0, null=True)
    year_1994 = models.FloatField(default=0, null=True)
    year_1995 = models.FloatField(default=0, null=True)
    year_1996 = models.FloatField(default=0, null=True)
    year_1997 = models.FloatField(default=0, null=True)
    year_1998 = models.FloatField(default=0, null=True)
    year_1999 = models.FloatField(default=0, null=True)
    year_2000 = models.FloatField(default=0, null=True)
    year_2001 = models.FloatField(default=0, null=True)
    year_2002 = models.FloatField(default=0, null=True)
    year_2003 = models.FloatField(default=0, null=True)
    year_2004 = models.FloatField(default=0, null=True)
    year_2005 = models.FloatField(default=0, null=True)
    year_2006 = models.FloatField(default=0, null=True)
    year_2007 = models.FloatField(default=0, null=True)
    year_2008 = models.FloatField(default=0, null=True)
    year_2009 = models.FloatField(default=0, null=True)
    year_2010 = models.FloatField(default=0, null=True)

class LiteracyRate(models.Model):
    countryname = models.CharField(max_length=200)
    countrycode = models.CharField(max_length=200)
    year_1990 = models.FloatField(default=0, null=True)
    year_1991 = models.FloatField(default=0, null=True)
    year_1992 = models.FloatField(default=0, null=True)
    year_1993 = models.FloatField(default=0, null=True)
    year_1994 = models.FloatField(default=0, null=True)
    year_1995 = models.FloatField(default=0, null=True)
    year_1996 = models.FloatField(default=0, null=True)
    year_1997 = models.FloatField(default=0, null=True)
    year_1998 = models.FloatField(default=0, null=True)
    year_1999 = models.FloatField(default=0, null=True)
    year_2000 = models.FloatField(default=0, null=True)
    year_2001 = models.FloatField(default=0, null=True)
    year_2002 = models.FloatField(default=0, null=True)
    year_2003 = models.FloatField(default=0, null=True)
    year_2004 = models.FloatField(default=0, null=True)
    year_2005 = models.FloatField(default=0, null=True)
    year_2006 = models.FloatField(default=0, null=True)
    year_2007 = models.FloatField(default=0, null=True)
    year_2008 = models.FloatField(default=0, null=True)
    year_2009 = models.FloatField(default=0, null=True)
    year_2010 = models.FloatField(default=0, null=True)

class WorkingAgeRate(models.Model):
    countryname = models.CharField(max_length=200)
    countrycode = models.CharField(max_length=200)
    year_1990 = models.FloatField(default=0, null=True)
    year_1991 = models.FloatField(default=0, null=True)
    year_1992 = models.FloatField(default=0, null=True)
    year_1993 = models.FloatField(default=0, null=True)
    year_1994 = models.FloatField(default=0, null=True)
    year_1995 = models.FloatField(default=0, null=True)
    year_1996 = models.FloatField(default=0, null=True)
    year_1997 = models.FloatField(default=0, null=True)
    year_1998 = models.FloatField(default=0, null=True)
    year_1999 = models.FloatField(default=0, null=True)
    year_2000 = models.FloatField(default=0, null=True)
    year_2001 = models.FloatField(default=0, null=True)
    year_2002 = models.FloatField(default=0, null=True)
    year_2003 = models.FloatField(default=0, null=True)
    year_2004 = models.FloatField(default=0, null=True)
    year_2005 = models.FloatField(default=0, null=True)
    year_2006 = models.FloatField(default=0, null=True)
    year_2007 = models.FloatField(default=0, null=True)
    year_2008 = models.FloatField(default=0, null=True)
    year_2009 = models.FloatField(default=0, null=True)
    year_2010 = models.FloatField(default=0, null=True)

    # social
    # cultural
    # border security
    # political
    # geographic
    # governmental programs (spending): welfare magnate effect
    # diasporas
    # language
