# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bilateral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_orig', models.CharField(max_length=200)),
                ('region_orig_id', models.IntegerField(default=0)),
                ('region_dest', models.CharField(max_length=200)),
                ('region_dest_id', models.IntegerField(default=0)),
                ('country_orig', models.CharField(max_length=200)),
                ('country_orig_id', models.IntegerField(default=0)),
                ('country_dest', models.CharField(max_length=200)),
                ('country_dest_id', models.IntegerField(default=0)),
                ('regionflow_1990', models.IntegerField(default=0)),
                ('regionflow_1995', models.IntegerField(default=0)),
                ('regionflow_2000', models.IntegerField(default=0)),
                ('regionflow_2005', models.IntegerField(default=0)),
                ('countryflow_1990', models.IntegerField(default=0)),
                ('countryflow_1995', models.IntegerField(default=0)),
                ('countryflow_2000', models.IntegerField(default=0)),
                ('countryflow_2005', models.IntegerField(default=0)),
                ('metadata', models.CharField(max_length=200)),
            ],
        ),
    ]
