# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20170507_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_1990',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_1991',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_1992',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_1993',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_1994',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_1995',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_1996',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_1997',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_1998',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_1999',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_2000',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_2001',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_2002',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_2003',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_2004',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_2005',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_2006',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_2007',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_2008',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_2009',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilityrates',
            name='year_2010',
            field=models.FloatField(default=0, null=True),
        ),
    ]
